### DISCUSSION TITLE
layer 是否可以根据内容实时变化

### DISCUSSION THREAD

**Discussion by cvpv** [layui/layui#1636] [建议]
当设置layer居中时候，当拖动浏览器宽度的时候，layui不会自动变化， 而是傻傻的待在原地。这似乎看起来有点呆。

在另一个场景中也有这样的问题：首先，我们的弹窗内容是动态的，因为弹窗内部包含tab标签栏，当用户在标签栏之间切换的时候，内容高度是剧烈变化的。目前layer无法支持。非常沮丧！

**Comment by cvpv** [comment]
希望能支持一种新的弹窗系统。

外部设置
```css
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    overflow: auto;
```
同时内部的弹窗内容设置margin auto等，各种方式，也能实现居中
个人觉得目前layer的js计算定位居中的方式在某些场景下面不适合

**Comment by cvpv** [comment]
不过有该需求的朋友别急，咱们可以暴力魔改，layer
首先使用下面的参数创建
```JavaScript
window.openPayDialog = function openPayDialog(opt) {
  const option = {
    type: 1,
    title: false,
    closeBtn: 1,
    anim: 5,
    shadeClose: true,
    scrollbar: false,
    skin: 'class-layer-custom-dialog',
    content: $('#dialogPay'),
    resize: false,
    move: false,
    fixed: true,
    area: 'auto',
  }
  window.layerindex = layer.open(option)
}
```
然后修改css
```css
/* #region 通用弹窗模板 */
.class-layer-custom-dialog {
  position: fixed !important;
  top: 0 !important;
  right: 0 !important;
  bottom: 0 !important;
  left: 0 !important;
  width: 100% !important;
  overflow: auto !important;
  background-color: transparent !important;
}
.layui-layer-page .layui-layer-content {
  height: auto !important;
  margin: 15vh auto 50px;
  background-color: #fff;
  width: var(--layer-custom-dialog-width, 50%);
}
.class-layer-custom-dialog .layui-layer-setwin {
  display: none;
}
/* #endregion 通用弹窗模板 */
```

这样就变成我们熟悉的element plus风格弹窗了！！

那内容宽度要修改怎么办？只能js修改style了，调整`--layer-custom-dialog-width`的值。

并且需要手动实现点击空白关闭，dialog头部底部等所有功能

而且丢失了layer的很多功能

![image](https://github.com/layui/layui/assets/84720311/418d4f56-dabf-43dd-8752-3fd8461ebf62)
