### DISCUSSION TITLE
【layer】当弹窗内容是动态变化的时候，如何使得layer能够自动水平居中？如果内容高度溢出后，如何实现layer能够出现全屏纵向滚动条？

### DISCUSSION THREAD

**Discussion by cvpv** [layui/layui#1637] [分享]
## 痛点
开发中遇到这样一个痛点，弹窗内容是动态变化，但是layer不会自动居中。
（layer在调整页面宽度的时候，会自动居中，我这边推测是监听了宽度变化，执行了重新计算。）

另外我的弹窗内容宽度高度是动态变化的，最高可能超出整个视窗屏幕。layer对溢出内容是显示内部滚动条（宽度自动），或者直接溢出隐藏。我希望能有个全屏滚动条，来使用户能够看到所有的内容（类似element plus）

## 临时修补方案
暴力覆盖layer的样式

首先使用下面的参数创建
```JavaScript
window.openPayDialog = function openPayDialog(opt) {
  const option = {
    type: 1,
    title: false,
    closeBtn: 1,
    anim: 5,
    shadeClose: true,
    scrollbar: false,
    skin: 'class-layer-custom-dialog',
    content: $('#dialogPay'),
    resize: false,
    move: false,
    fixed: true,
    area: 'auto',
  }
  window.layerindex = layer.open(option)
}
```
然后修改css
```css
/* #region 通用弹窗模板 */
.class-layer-custom-dialog {
  position: fixed !important;
  top: 0 !important;
  right: 0 !important;
  bottom: 0 !important;
  left: 0 !important;
  width: 100% !important;
  overflow: auto !important;
  background-color: transparent !important;
}
.layui-layer-page .layui-layer-content {
  height: auto !important;
  margin: 15vh auto 50px;
  background-color: #fff;
  width: var(--layer-custom-dialog-width, 50%);
}
.class-layer-custom-dialog .layui-layer-setwin {
  display: none;
}
/* #endregion 通用弹窗模板 */
```
这样就变成我们熟悉的element plus风格弹窗了！！
