### DISCUSSION TITLE
表格工具栏的位置如何修改到表格底部

### DISCUSSION THREAD

**Discussion by Python-tool** [layui/layui#1927] [问答] [answered]
表格工具栏的位置可以修改到表格底部吗？该如何实现。

**Comment by LSL1618** [comment]
表格工具栏是固定在顶部的。表格底部一般是分页栏的位置。

**Reply by Python-tool** [reply]
是的，有没有办法让工具栏的按钮放到分页栏里面，也就是表格右下角

**Reply by LSL1618** [reply]
这个没有的，建议把工具类按钮放到搜索栏，如果有搜索栏的话。

**Comment by hjingsuper** [comment, marked as answer]
1.[官网实例自定义分页](https://layui.dev/docs/2/table/#demo-page)中按钮是可以放在底部的
2.要放在table右下角，添加css样式即可 [https://codepen.io/hjingsuper/pen/GRaZLpz](https://codepen.io/hjingsuper/pen/GRaZLpz)

```css
  .layui-table-page .layui-table-pagebar{
    float: left;
  }
```
