### DISCUSSION TITLE
🌊 退潮三周年，分享下当年 Layui 官网弹出公告主题

### DISCUSSION THREAD

**Discussion by sentsim** [layui/layui#2267] [分享]
熟悉 Layui 的同学，应该都还记得 2021 年 10 月原官网的那个让人五味杂陈的弹出公告吧。

当我们回首过往，更多是对自然周期的体悟。Layui 在那一年所经历的退潮，实际上也伴随着国内的「信创供需」急速下滑的大环境驱使，后来整个互联网的景气度，也逐渐回到了它该有的状态。所谓「无极本无始，无始方无终，因果两相去，造化生海平。」

那个蓝绿渐变的背景已然定格，而它上面的文字却已被岁月冲刷，留下一个可被更多人任意书写的「内容」。

![image](https://github.com/user-attachments/assets/689ab0e4-4495-4fba-9b4e-982261497e1a)

---

```css
<style>
.site-popup-notice{background-image: linear-gradient(to right,#359FD4,#36B5C8,#25D8AB); }
.site-popup-notice .layui-layer-title{border-bottom-color: rgba(255,255,255,.1);}
.site-popup-notice .layui-layer-content{padding: 16px; color: #fff;}
</style>
```

```js
layer.open({
  type: 1,
  title: "公告",
  area: layui.device().mobile ? ["90%", "90%"] : ["800px", "520px"],
  shade: false,
  id: "LAY_Notice", // 设定一个id，防止重复弹出
  skin: "site-popup-notice",
  resize: false,
  content: "内容"
});
```
