### DISCUSSION TITLE
手机时间范围选择 。有问题只显示了一半，有好的处理方案吗？

### DISCUSSION THREAD

**Discussion by sggcn** [layui/layui#2371] [问答] [answered]
![image](https://github.com/user-attachments/assets/89dd0ef9-8d7a-4a3a-a504-b84123d4f0d5)

**Comment by LSL1618** [comment]
可以将开始时间和结束时间拆成2个独立的时间选择器。

**Reply by sggcn** [reply]
。。。这个是个办法。  但是不是我想要的效果

**Reply by LSL1618** [reply]
手机屏幕就那么点大，时间选择器又没有其它大小模式。

**Comment by bxjt123** [comment]
或者旋转屏幕至横屏，也许能显示的下

**Comment by Sight-wcg** [comment, marked as answer]
将下面的代码添加到你的公共模块，按照注释说明使用即可。按照 Android WebView 中原生组件的常用方案，将日期面板居中显示，尽可能适配更多设备类型。
```js
      layui.util.on('laydate-mobile', {
        /**
         * laydate 移动端补丁
         * 给 laydate 绑定元素上添加 laydate-mobile="enable" 即可开启移动端适配
         * data-trigger-width 属性设置触发宽度，默认 768
         * 建议主动给输入框添加 readonly 属性，避免弹出软键盘
         * 
         * @example
         * ```
         * <input laydate-mobile="enable" type="text" class="layui-input" id="test" >
         * <input laydate-mobile="enable" data-trigger-width="900" type="text" class="layui-input" id="test1" >
         * ```
         */
        enable: function (e) {
          var targetEl = $(this);
          var triggerWidth = parseFloat(targetEl.data('trigger-width')) || 768;
          
          if (window.innerWidth > triggerWidth) return;
          /**
           * @param {string} selector
           * @returns {Promise<HTMLElement[]>}
           */
          var waitForElements = function (selector) {
            return new Promise(function (resolve) {
              if (document.querySelectorAll(selector).length > 0) {
                return resolve(document.querySelectorAll(selector));
              }
              var observer = new MutationObserver(function () {
                if (document.querySelectorAll(selector).length > 0) {
                  resolve(document.querySelectorAll(selector));
                  observer.disconnect();
                }
              });
              try {
                observer.observe(document.body, {
                  childList: true,
                  subtree: true,
                });
              } catch {
                setTimeout(function () {
                  resolve(waitForElements(selector));
                }, 100);
              }
            });
          }
          waitForElements('#layui-laydate' + targetEl.attr('lay-key')).then(function (panelEl) {
            var panelEl = $(panelEl[0]);
            var isPatched = panelEl.hasClass('laydate-mobile');
            if (isPatched) return;
            var isRange = panelEl.hasClass('layui-laydate-range');
            var isRangeLinked = panelEl.hasClass('layui-laydate-linkage');
            var shortcutEl = panelEl.find('.layui-laydate-shortcut');
            panelEl.addClass('laydate-mobile');
            // 范围选择添加 tab
            if (isRange) {
              panelEl.addClass('laydate-range-active-start');
              panelEl.prepend([
                '<div class="layui-tab layui-tab-brief" lay-unauto lay-filter="laydate-mobile-filter-tab">',
                '<ul class="layui-tab-title">',
                '<li class="layui-this" lay-id="start">开始日期</li>',
                '<li lay-id="end">结束日期</li>',
                '</ul>',
                '</div>'
              ].join(''));

              layui.element.render('tab', 'laydate-mobile-filter-tab');
              var tabEl = $('[lay-filter="laydate-mobile-filter-tab"]');
              tabEl.on('click', 'li', function () {
                layui.element.tabChange('laydate-mobile-filter-tab', $(this).attr('lay-id'));
              })
              layui.element.on('tab(laydate-mobile-filter-tab)', function (data) {
                if (data.id === 'start') {
                  panelEl.addClass('laydate-range-active-start').removeClass('laydate-range-active-end');
                } else if (data.id === 'end') {
                  panelEl.addClass('laydate-range-active-end').removeClass('laydate-range-active-start');
                }
              });

              // 只在时间选择器显示 tab
              if (isRangeLinked) {
                var timePickerSwitchBtn = panelEl.find('.laydate-btns-time')
                tabEl.hide();
                if (timePickerSwitchBtn.length > 0) {
                  timePickerSwitchBtn.on('click', function () {
                    var type = timePickerSwitchBtn.attr('lay-type');
                    if (type === 'date') {
                      tabEl.show();
                    } else if (type === 'datetime') {
                      tabEl.hide();
                    }
                  })
                }
              }
            }

            // 快捷面板移动到底部
            if (shortcutEl.length > 0) {
              shortcutEl.insertAfter(panelEl.find('.layui-laydate-footer'))
            }
          });
        }
      })
```

```css
    .laydate-mobile {
      width: auto !important;
      position: fixed !important;
      top: 50% !important;
      left: 50% !important;
      transform: translate(-50%, -50%) !important;
    }

    .laydate-mobile.layui-laydate-range .laydate-time-show .layui-laydate-header {
      display: none;
    }

    .laydate-mobile.layui-laydate-range .layui-laydate-preview {
      display: none;
    }

    .laydate-mobile.layui-laydate-range .layui-laydate-main {
      max-width: unset !important;
    }

    .laydate-range-active-start .laydate-main-list-1 {
      display: none;
    }

    .laydate-range-active-end .laydate-main-list-0 {
      display: none;
    }

    .laydate-range-active-end.layui-laydate-linkage .laydate-main-list-0:not(.laydate-time-show),
    .laydate-range-active-start.layui-laydate-linkage .laydate-main-list-0:not(.laydate-time-show) {
      display: inline-block !important;
    }

    .laydate-range-active-end.layui-laydate-linkage .laydate-main-list-1:not(.laydate-time-show),
    .laydate-range-active-start.layui-laydate-linkage .laydate-main-list-1:not(.laydate-time-show) {
      display: none !important;
    }

    .laydate-mobile .layui-tab-brief>.layui-tab-title .layui-this {
      color: #16baaa !important;
      background-color: unset !important;
    }

    .laydate-mobile .layui-laydate-main:not(.laydate-ym-show, .laydate-time-show) .laydate-next-m {
      display: block !important;
    }

    .laydate-mobile .laydate-next-y {
      display: block !important;
    }

    .laydate-mobile .layui-tab .layui-tab-title {
      display: flex;
    }

    .laydate-mobile .layui-tab .layui-tab-title li {
      flex: 1;
    }

    .laydate-mobile .layui-laydate-shortcut {
      display: flex;
      flex-wrap: wrap;
      width: auto;
      max-width: 272px;
    }
```
