### DISCUSSION TITLE
封装的常用时间范围选择器

### DISCUSSION THREAD

**Discussion by sggcn** [layui/layui#2380] [分享]
**PC端**
![image](https://github.com/user-attachments/assets/341d4845-0e0d-4968-8ee5-1cf2d02b6c57)
**手机端**
![image](https://github.com/user-attachments/assets/86692636-0e4c-43eb-b4f3-e7ee950d9ca9)

**如何使用**
rangeDateDay()使用此函数

**JS代码**
  感谢 @Sight-wcg 提供手机适配代码 
```html
<input id="rangeDate" type="text" readonly placeholder="执行时间" class="layui-input" />
```

```js
//渲染时间
rangeDateDay({
	id: '#rangeDate',
	html: {
		appendBeginInputName:"beginBuyTime",
		appendEndInputName:"endBuyTime"
		
	}
});

/**
 * 获取时间范围快捷键 常量数据
 */
function getRangeDateShortcuts() {
	return {
		//快捷选择天
		JT: {
			text: "今天",
			value: function() {
				var date = new Date();
				var year = date.getFullYear();
				var month = date.getMonth();
				var day = date.getDay();
				return [
					date,
					date
				];
			}
		},
		ZT: {
			text: "昨天",
			value: function() {
				var date = new Date();
				var year = date.getFullYear();
				var month = date.getMonth();
				var day = date.getDay();
				return [
					new Date(year, month, day - 1),
					new Date(year, month, day - 1)
				];
			}
		},
		QT: {
			text: "前天",
			value: function() {
				var date = new Date();
				var year = date.getFullYear();
				var month = date.getMonth();
				var day = date.getDay();
				return [
					new Date(year, month, day - 2),
					new Date(year, month, day - 2)
				];
			}
		},

		//快捷选择月
		BY: {
			text: "本月",
			value: function() {
				var date = new Date();
				var year = date.getFullYear();
				var month = date.getMonth();
				var day = date.getDay();
				return [
					new Date(year, month, 1),
					new Date(year, month + 1, 0),
				];
			}
		},
		SGY: {
			text: "上个月",
			value: function() {
				var date = new Date();
				var year = date.getFullYear();
				var month = date.getMonth();
				var day = date.getDay();
				return [
					new Date(year, month - 1, 1),
					new Date(year, month, 0),
				];
			}
		},
		SSGY: {
			text: "上上个月",
			value: function() {
				var date = new Date();
				var year = date.getFullYear();
				var month = date.getMonth();
				var day = date.getDay();
				return [
					new Date(year, month - 2, 1),
					new Date(year, month - 1, 0),
				];
			}
		},
		//快捷选择年
		JN: {
			text: "今年",
			value: function() {
				var date = new Date();
				var year = date.getFullYear();
				var month = date.getMonth();
				var day = date.getDay();
				return [
					new Date(year, 0, 1),
					new Date(year, 12, 0),
				];
			}
		},
		QN: {
			text: "去年",
			value: function() {
				var date = new Date();
				var year = date.getFullYear();
				var month = date.getMonth();
				var day = date.getDay();
				return [
					new Date(year - 1, 0, 1),
					new Date(year - 1, 12, 0),
				];
			}
		},
		DQN: {
			text: "大去年",
			value: function() {
				var date = new Date();
				var year = date.getFullYear();
				var month = date.getMonth();
				var day = date.getDay();
				return [
					new Date(year - 2, 0, 1),
					new Date(year - 2, 12, 0),
				];
			}
		},

		//快捷选择 近期时间
		J7T: {
			text: "近7天",
			value: function() {
				var date = new Date();
				var year = date.getFullYear();
				var month = date.getMonth();
				var day = date.getDay();
				return [
					new Date(year, month, day - 6),
					date
				];
			}
		},
		J30T: {
			text: "近30天",
			value: function() {
				var date = new Date();
				var year = date.getFullYear();
				var month = date.getMonth();
				var day = date.getDay();
				return [
					new Date(year, month, day - 29),
					date
				];
			}
		},
		J60T: {
			text: "近60天",
			value: function() {
				var date = new Date();
				var year = date.getFullYear();
				var month = date.getMonth();
				var day = date.getDay();
				return [
					new Date(year, month, day - 59),
					date
				];
			}
		},
		J90T: {
			text: "近90天",
			value: function() {
				var date = new Date();
				var year = date.getFullYear();
				var month = date.getMonth();
				var day = date.getDay();
				return [
					new Date(year, month, day - 89),
					date
				];
			}
		},
		J365T: {
			text: "近365天",
			value: function() {
				var date = new Date();
				var year = date.getFullYear();
				var month = date.getMonth();
				var day = date.getDay();
				return [
					new Date(year, month, day - 364),
					date
				];
			}
		}
	}
}


/**
 * 天选择范围 laydate 的封装 https://layui.dev/docs/2/laydate/#options.value
 * 建议主动给输入框添加 readonly 属性，避免弹出软键盘
 * 移动端补丁:
 * 		给 laydate 绑定元素上添加 laydate-mobile="enable" 即可开启移动端适配
 * 		data-trigger-width 属性设置触发宽度，默认 768
 * 		如1：<input laydate-mobile="enable" type="text" class="layui-input" id="test" >
 * 		如2：<input laydate-mobile="enable" data-trigger-width="900" type="text" class="layui-input" id="test1" >
 * @param {Object} opt
 * opt.id html元素id 需要# 如：#idName
 * opt.initValueType 如 BY,JN,J30T(本月，今年，近30天) 等...
 * opt.values[] 初始值 如value: ['1900-01-01','2100-01-01']
 * opt.done 日期时间被切换完成后的回调函数。 done: function(doneInfo) 
 * opt.shortcuts 用于开启面板左侧的快捷选择栏 laydat
 * opt.html.appendBeginInputName 追加隐藏的inputName
 * opt.html.appendEndInputName 追加隐藏的inputName
 */
function rangeDateDay(opt) {
	if (!opt.initValueType) opt.initValueType = "BY";
	if (!opt.done) opt.done = function(v) {};
	if (!opt.values) opt.values = [];
	let RDS = getRangeDateShortcuts();

	if (opt.values.length == null || opt.values == undefined || opt.values.length == 0) {
		let valueType = RDS[opt.initValueType].value()
		opt.values[0] = util.toDateString(valueType[0], 'yyyy-MM-dd');
		opt.values[1] = util.toDateString(valueType[1], 'yyyy-MM-dd');
	}

	if (!opt.shortcuts) opt.shortcuts = [
		RDS.BY, RDS.SGY, RDS.SSGY,
		RDS.JN, RDS.QN, RDS.DQN,
		RDS.J30T, RDS.J90T, RDS.J365T,
	]

	rangeDate({
		...opt,
		values: opt.values,
		rangeLinked: true,
		done: function(v) {
			opt.done(v)
		}
	});
}


/**
 * 时间范围渲染 laydate 的封装 https://layui.dev/docs/2/laydate/#options.value
 * 建议主动给输入框添加 readonly 属性，避免弹出软键盘
 * 移动端补丁:
 * 		给 laydate 绑定元素上添加 laydate-mobile="enable" 即可开启移动端适配
 * 		data-trigger-width 属性设置触发宽度，默认 768
 * 		如1：<input laydate-mobile="enable" type="text" class="layui-input" id="test" >
 * 		如2：<input laydate-mobile="enable" data-trigger-width="900" type="text" class="layui-input" id="test1" >
 * 
 * @param {Object} opt
 * opt.id html元素id 需要# 如：#idName
 * opt.values[] 初始值 如value: ['1900-01-01','2100-01-01']
 * opt.html.appendBeginInputName 追加隐藏的inputName
 * opt.html.appendEndInputName 追加隐藏的inputName
 * opt.type 	year|month|date|time|datetime
 * opt.done 日期时间被切换完成后的回调函数。 done: function(doneInfo) 
 * opt.shortcuts 用于开启面板左侧的快捷选择栏 laydat
 */
function rangeDate(opt) {
	if (!opt.id) return;
	if (!opt.values) opt.values = [];
	if (!opt.type) opt.type = "date";
	if (!opt.done) opt.done = function(doneInfo) {};
	if (!opt.shortcuts) opt.shortcuts = [];



	if (opt.html) {
		//默认input
		if (!opt.html.appendBeginInputName && !opt.html.appendEndInputName) {
			opt.html.appendBeginInputName = "beginDate";
			opt.html.appendEndInputName = "endDate";
		}

		//存在就不添加
		if ($("#" + opt.html.appendBeginInputName).length == 0 &&
			$("#" + opt.html.appendEndInputName).length == 0) {
			$(opt.id).after(`<input id="${opt.html.appendBeginInputName}" name="${opt.html.appendBeginInputName}"
			  style="display: none"></input>`);
			$(opt.id).after(`<input id="${opt.html.appendEndInputName}" name="${opt.html.appendEndInputName}"
			  style="display: none"></input>`);
		}
	}
	let value = "";
	if (opt.values[0] && opt.values[1]) {
		value = opt.values[0] + " - " + opt.values[1]
		if (opt.html) {
			var beginInput = $("#" + opt.html.appendBeginInputName);
			var endInput = $("#" + opt.html.appendEndInputName);
			beginInput.val(opt.values[0]);
			endInput.val(opt.values[1]);
		}
	}

	// 日期范围
	laydate.render({
		elem: opt.id,
		value: value,
		type: opt.type,
		range: true,
		done: function(value, date, endDate) {
			let dates = value.split(" - ");
			var doneInfo = {
				value: value,
				beginDate: date,
				endDate: endDate,
				values: dates,
			}
			if (opt.html) {
				var beginInput = $("#" + opt.html.appendBeginInputName);
				var endInput = $("#" + opt.html.appendEndInputName);
				beginInput.val(dates[0]);
				endInput.val(dates[1]);
			}

			// console.log(JSON.stringify(doneInfo))
			opt.done(doneInfo);
		},
		shortcuts: opt.shortcuts
	});


	//移动端补丁
	layui.util.on('laydate-mobile', {
		/**
		 * laydate 移动端补丁
		 * 给 laydate 绑定元素上添加 laydate-mobile="enable" 即可开启移动端适配
		 * data-trigger-width 属性设置触发宽度，默认 768
		 * 建议主动给输入框添加 readonly 属性，避免弹出软键盘
		 * 
		 * @example
		 * ```
		 * <input laydate-mobile="enable" type="text" class="layui-input" id="test" >
		 * <input laydate-mobile="enable" data-trigger-width="900" type="text" class="layui-input" id="test1" >
		 * ```
		 */
		enable: function(e) {
			var targetEl = $(this);
			var triggerWidth = parseFloat(targetEl.data('trigger-width')) || 768;

			if (window.innerWidth > triggerWidth) return;
			/**
			 * @param {string} selector
			 * @returns {Promise<HTMLElement[]>}
			 */
			var waitForElements = function(selector) {
				return new Promise(function(resolve) {
					if (document.querySelectorAll(selector).length > 0) {
						return resolve(document.querySelectorAll(selector));
					}
					var observer = new MutationObserver(function() {
						if (document.querySelectorAll(selector).length >
							0) {
							resolve(document.querySelectorAll(selector));
							observer.disconnect();
						}
					});
					try {
						observer.observe(document.body, {
							childList: true,
							subtree: true,
						});
					} catch {
						setTimeout(function() {
							resolve(waitForElements(selector));
						}, 100);
					}
				});
			}
			waitForElements('#layui-laydate' + targetEl.attr('lay-key')).then(function(
				panelEl) {
				var panelEl = $(panelEl[0]);
				var isPatched = panelEl.hasClass('laydate-mobile');
				if (isPatched) return;
				var isRange = panelEl.hasClass('layui-laydate-range');
				var isRangeLinked = panelEl.hasClass('layui-laydate-linkage');
				var shortcutEl = panelEl.find('.layui-laydate-shortcut');
				panelEl.addClass('laydate-mobile');
				// 范围选择添加 tab
				if (isRange) {
					panelEl.addClass('laydate-range-active-start');
					panelEl.prepend([
						'<div class="layui-tab layui-tab-brief" lay-unauto lay-filter="laydate-mobile-filter-tab">',
						'<ul class="layui-tab-title">',
						'<li class="layui-this" lay-id="start">开始日期</li>',
						'<li lay-id="end">结束日期</li>',
						'</ul>',
						'</div>'
					].join(''));

					layui.element.render('tab', 'laydate-mobile-filter-tab');
					var tabEl = $('[lay-filter="laydate-mobile-filter-tab"]');
					tabEl.on('click', 'li', function() {
						layui.element.tabChange('laydate-mobile-filter-tab', $(
							this).attr('lay-id'));
					})
					layui.element.on('tab(laydate-mobile-filter-tab)', function(data) {
						if (data.id === 'start') {
							panelEl.addClass('laydate-range-active-start')
								.removeClass('laydate-range-active-end');
						} else if (data.id === 'end') {
							panelEl.addClass('laydate-range-active-end')
								.removeClass('laydate-range-active-start');
						}
					});

					// 只在时间选择器显示 tab
					if (isRangeLinked) {
						var timePickerSwitchBtn = panelEl.find('.laydate-btns-time')
						tabEl.hide();
						if (timePickerSwitchBtn.length > 0) {
							timePickerSwitchBtn.on('click', function() {
								var type = timePickerSwitchBtn.attr('lay-type');
								if (type === 'date') {
									tabEl.show();
								} else if (type === 'datetime') {
									tabEl.hide();
								}
							})
						}
					}
				}

				// 快捷面板移动到底部
				if (shortcutEl.length > 0) {
					shortcutEl.insertAfter(panelEl.find('.layui-laydate-footer'))
				}
			});
		}
	})
}

```

**手机适配css**
```css
    .laydate-mobile {
      width: auto !important;
      position: fixed !important;
      top: 50% !important;
      left: 50% !important;
      transform: translate(-50%, -50%) !important;
    }

    .laydate-mobile.layui-laydate-range .laydate-time-show .layui-laydate-header {
      display: none;
    }

    .laydate-mobile.layui-laydate-range .layui-laydate-preview {
      display: none;
    }

    .laydate-mobile.layui-laydate-range .layui-laydate-main {
      max-width: unset !important;
    }

    .laydate-range-active-start .laydate-main-list-1 {
      display: none;
    }

    .laydate-range-active-end .laydate-main-list-0 {
      display: none;
    }

    .laydate-range-active-end.layui-laydate-linkage .laydate-main-list-0:not(.laydate-time-show),
    .laydate-range-active-start.layui-laydate-linkage .laydate-main-list-0:not(.laydate-time-show) {
      display: inline-block !important;
    }

    .laydate-range-active-end.layui-laydate-linkage .laydate-main-list-1:not(.laydate-time-show),
    .laydate-range-active-start.layui-laydate-linkage .laydate-main-list-1:not(.laydate-time-show) {
      display: none !important;
    }

    .laydate-mobile .layui-tab-brief>.layui-tab-title .layui-this {
      color: #16baaa !important;
      background-color: unset !important;
    }

    .laydate-mobile .layui-laydate-main:not(.laydate-ym-show, .laydate-time-show) .laydate-next-m {
      display: block !important;
    }

    .laydate-mobile .laydate-next-y {
      display: block !important;
    }

    .laydate-mobile .layui-tab .layui-tab-title {
      display: flex;
    }

    .laydate-mobile .layui-tab .layui-tab-title li {
      flex: 1;
    }

    .laydate-mobile .layui-laydate-shortcut {
      display: flex;
      flex-wrap: wrap;
      width: auto;
      max-width: 272px;
    }
```
