### ISSUE TITLE
收缩左侧菜单时，表格右侧出来了一个空白列

### ISSUE THREAD

**Issue by davinma** [layui/layui#320]
在[官方样例](https://www.layui.com/admin/pro/#/component/table/page)中，点击顶部的 <kbd>侧边伸缩</kbd> 图标时，页面表格的右侧出现了一列空白（一块空白）。

目前暂时的解决方案，把：

``` CSS
.layui-table-view .layui-table {
    position: relative;
    width: auto;
    margin: 0;
}
```

改成：

``` CSS
.layui-table-view .layui-table {
    position: relative;
    width: 100%;
    margin: 0;
}
```

即把表格宽度值改为 `100%`，不知道可有其他好的方法，请告知下，谢谢！
