### ISSUE TITLE
数据表格自动渲染 lay-data 属性不能用 v2.4.5

### ISSUE THREAD

**Issue by tlxfif** [layui/layui#422]
有个需求需要用到自动渲染
希望能用上导出功能
```java script
<table class="layui-table" >
<tr>
      <th >1</th>
      <th >2</th>
    </tr>
</table>
```
这样可以正常显示
```java script
<table class="layui-table"  lay-data="{height:315}">
<tr>
      <th >1</th>
      <th >2</th>
    </tr>
</table>
```
这样不行，只要带上lay-data 就是不行

带上lay-data时  当前table 出现
```css
.layui-table[lay-data] {
    display: none;
}
```
当我手动关闭该css，table被显示出来，lay-data="{height:315}“ 没有起到作用

应该是我这边可能操作有问题，各位大佬麻烦看一下，谢谢：）
