### ISSUE TITLE
table 开启头部工具栏后，页面同时存在多个table时筛选列下拉显示被下方表格遮挡

### ISSUE THREAD

**Issue by No5972** [layui/layui#763]
https://fly.layui.com/jie/47107/
如果修改下方表格头工具栏层叠的话会导致下方表格头工具栏点击选择列展开的菜单无法显示出超过头工具栏高度的部分（下方表格的头工具栏的选择列菜单也会显示不完整）

![wWUYkR.png](https://s1.ax1x.com/2020/09/17/wWUYkR.png)

修改层叠后：
```css
.layui-table-view[lay-id=td2] .layui-table-tool {
    z-index: 0 !important;
}
```
![wWUG79.png](https://s1.ax1x.com/2020/09/17/wWUG79.png)
